### ISSUE TITLE
Ask users to clone the repository in their USER scratch directory in /scratch/nf33

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/workshop-training-2023#1]
@headmetal, @dougiesquire @rhaegar325 

Users signing up for the training will have a directory in `/scratch/nf33`. We should ask them to clone the repository there.
They should also be instructed to navigate to that directory after starting their ARE Jupyter session.

**Comment by headmetal** [comment]
I presume users will be provided with this directory name early so they can do the prerequisite setup before arriving?

If its helpful to anyone, I've included the following text in the [ARE_setup_guide](https://github.com/ACCESS-NRI/NRI-Workshop2023-MED/edit/main/ARE_setup_guide.md) (if others want to do the same):

" Clone the workshop tutorials of interest found in the [NRI-Workshop2023-MED repo](https://github.com/ACCESS-NRI/NRI-Workshop2023-MED/tree/main) to the personal user directory on `scratch/nf33` that has been provided to you. "

**Comment by rbeucher** [comment]
I think by default you get a directory with your username in scratch. Check if you can see yours.

**Comment by headmetal** [comment]
Just had a look and I don't have a directory in `scratch/nf33` - I count n = 19 in there. That seems like a low amount...

**Comment by rhaegar325** [comment]
Yes, I don't have a directory at `scratch/nf33` as well

**Comment by rbeucher** [comment]
Ok needs to be created
