### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/workshop-training-2023#10]
The name of this repo currently includes "MED", but it is no longer just MED content

**Comment by dougiesquire** [comment]
@rbeucher, @MartinDix  thoughts on what this should be called? Would be good to rename soon as I'd like to make sure the name is correct in any documentation.

How about `workshop-training-2023`?

**Comment by MartinDix** [comment]
Ok with me

**Comment by rbeucher** [comment]
Yes OK with me

**Comment by dougiesquire** [comment]
I don't have permission to change this. @rbeucher can you do it?

**Comment by rbeucher** [comment]
Oh sure. Will do.
