### ISSUE TITLE
Expand git cloning / user folder instructions

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/workshop-training-2023#11]
Add more detailed git cloning / user directory creation instructions for Step 0 in [ARE_setup_guide.md](https://github.com/ACCESS-NRI/NRI-Workshop2023-MED/blob/main/ARE_setup_guide.md)

@dougiesquire @rbeucher

**Comment by rbeucher** [comment]
We probably need a section for VDI too.

**Comment by headmetal** [comment]
@dougiesquire has added in updated git cloning instructions. Thanks!

**Comment by rbeucher** [comment]
Thanks @dougiesquire
