### ISSUE TITLE
Update ARE instructions

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/workshop-training-2023#17]
Need to bring together all ARE instructions (SSH, Jupyter and VDI) into one coherent document.

**Comment by rbeucher** [comment]
@headmetal are you working on this?

**Comment by rbeucher** [comment]
One important thing is what @rhaegar325 has added to the ILAMB document #16

This is specific to xp65

**Comment by headmetal** [comment]
Yep - will have them all done by later today / tomorrow morning

**Comment by dougiesquire** [comment]
@headmetal and I discussed this offline a little. Thoughts:
- Move the instructions to clone the directory into a separate document or into the README,
- Move ARE_setup_guide.md into the intake directory and edit it slightly to make specific to the Intake tutorials (it pretty much already is),
- Add project prerequisite information to the sections on each training set (Intake, ILAMB, etc) in the README.

Does this work for you @rbeucher, @rhaegar325?

**Comment by rbeucher** [comment]
1. I think the README is fine for that. We have added a note in the material that says...if you don't have the folder, please clone blabla...
2. Yes good.
3. I think it is kinda there already no?

**Comment by rbeucher** [comment]
Note that #16 is only relevant for the ESMValTool exercise

**Comment by dougiesquire** [comment]
> 3. I think it is kinda there already no?

Yup, I think @headmetal was just going to make sure it was there for all the different training stages

**Comment by headmetal** [comment]
Its _mostly_ there - I just need to make a few tweaks.

Will wait until this skillshare session is finished to do it

**Comment by rbeucher** [comment]
The ARE instructions in the different tutorials use some assets that sit in different places.. Maybe we should consolidate that at some point...

**Comment by dougiesquire** [comment]
> * Move the instructions to clone the directory into a separate document or into the README,

Done in #21

**Comment by dougiesquire** [comment]
> - Move ARE_setup_guide.md into the intake directory and edit it slightly to make specific to the Intake tutorials (it pretty much already is),

This is now also done. 

> - Add project prerequisite information to the sections on each training set (Intake, ILAMB, etc) in the README.

@headmetal, the README has now had quite a revamp and is significantly more concise (which is a good thing). The project prerequisites are listed in all the individual training docs, so maybe we don't need them in the README after all?
