### ISSUE TITLE
Wrong link for ARE in setup docs

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/workshop-training-2023#6]
https://github.com/ACCESS-NRI/NRI-Workshop2023-MED/blob/c4088046fbe68cbfbe4f9ab7a5f9e9f1214c17cb/ARE_setup_guide.md?plain=1#L11 uses https://are-auth.nci.org.au/ which doesn't work

Should be https://are.nci.org.au/

**Comment by headmetal** [comment]
Pull request approved - thanks Martin
